/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example;

/**
 *
 * @author ACER
 */
public class ClientesReservacionZz extends javax.swing.JPanel {

    /**
     * Creates new form ClientesReservacionZz
     */
    public ClientesReservacionZz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        esperaAprox = new javax.swing.JTextField();
        enviarALaEsperaButton = new javax.swing.JButton();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre del cliente");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tiempo de espera");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        nombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        nombreCliente.setText("jTextField1");
        nombreCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 2, true));
        nombreCliente.setCaretColor(new java.awt.Color(0, 102, 255));
        nombreCliente.setDisabledTextColor(new java.awt.Color(51, 153, 255));
        bg.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 200, 30));

        esperaAprox.setBackground(new java.awt.Color(255, 255, 255));
        esperaAprox.setText("jTextField1");
        esperaAprox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 2, true));
        esperaAprox.setCaretColor(new java.awt.Color(0, 102, 255));
        esperaAprox.setDisabledTextColor(new java.awt.Color(51, 153, 255));
        bg.add(esperaAprox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 200, 30));

        enviarALaEsperaButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        enviarALaEsperaButton.setForeground(new java.awt.Color(0, 0, 0));
        enviarALaEsperaButton.setText("Enviar a la espera");
        enviarALaEsperaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarALaEsperaButtonActionPerformed(evt);
            }
        });
        bg.add(enviarALaEsperaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enviarALaEsperaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarALaEsperaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarALaEsperaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton enviarALaEsperaButton;
    private javax.swing.JTextField esperaAprox;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombreCliente;
    // End of variables declaration//GEN-END:variables
}
