/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example;
import com.GestorBd.GestorBd;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;



/**
 *
 * @author ACER
 */
public class verReservaZz extends javax.swing.JPanel {



    /**
     * Creates new form verReservaZz
     */
    public verReservaZz() {
        initComponents();
        
    }
                    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        reservacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeroMesa = new javax.swing.JTextField();
        horaReservacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        numeroPerso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fechaReservacion = new javax.swing.JTextField();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        reservacion.setForeground(new java.awt.Color(0, 0, 0));
        reservacion.setText("Confirmar reserva");
        reservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservacionActionPerformed(evt);
            }
        });
        bg.add(reservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 230, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Hora de la reservación");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Número de mesa");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        numeroMesa.setBackground(new java.awt.Color(255, 255, 255));
        numeroMesa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 2, true));
        numeroMesa.setCaretColor(new java.awt.Color(0, 102, 255));
        numeroMesa.setDisabledTextColor(new java.awt.Color(51, 153, 255));
        bg.add(numeroMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 200, 30));

        horaReservacion.setBackground(new java.awt.Color(255, 255, 255));
        horaReservacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 2, true));
        horaReservacion.setCaretColor(new java.awt.Color(0, 102, 255));
        horaReservacion.setDisabledTextColor(new java.awt.Color(51, 153, 255));
        bg.add(horaReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 220, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre del cliente");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        nombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        nombreCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 2, true));
        nombreCliente.setCaretColor(new java.awt.Color(0, 102, 255));
        nombreCliente.setDisabledTextColor(new java.awt.Color(51, 153, 255));
        bg.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 200, 30));

        numeroPerso.setBackground(new java.awt.Color(255, 255, 255));
        numeroPerso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 2, true));
        numeroPerso.setCaretColor(new java.awt.Color(0, 102, 255));
        numeroPerso.setDisabledTextColor(new java.awt.Color(51, 153, 255));
        bg.add(numeroPerso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 200, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Número de personas");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fecha de la reservación");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        fechaReservacion.setBackground(new java.awt.Color(255, 255, 255));
        fechaReservacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 2, true));
        fechaReservacion.setCaretColor(new java.awt.Color(0, 102, 255));
        fechaReservacion.setDisabledTextColor(new java.awt.Color(51, 153, 255));
        bg.add(fechaReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservacionActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = nombreCliente.getText();
            String fecha = fechaReservacion.getText();
            String hora = horaReservacion.getText();
            int numeroPer = Integer.parseInt(numeroPerso.getText());
            int numeroM = Integer.parseInt(numeroMesa.getText());

            if (nombre.isEmpty() || fecha.isEmpty() || hora.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos deben ser completados.");
                return;
            }

            LocalTime horaReserva = LocalTime.parse(hora, DateTimeFormatter.ofPattern("HH:mm"));
            LocalTime horaFin = horaReserva.plusHours(2);

            Reservas reserva = new Reservas(0, nombre, horaReserva, horaFin, numeroPer, numeroM, fecha);
            controlBd.insertarReserva(reserva);
          
            //Confirmación de la reservación
            JOptionPane.showMessageDialog(this, "Reserva añadida con éxito.");
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error: Número de personas o mesa inválido.");
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "Error: Formato de hora incorrecto (HH:mm).");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + ex.getMessage());
        }
    }//GEN-LAST:event_reservacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JTextField fechaReservacion;
    private javax.swing.JTextField horaReservacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTextField numeroMesa;
    private javax.swing.JTextField numeroPerso;
    private javax.swing.JButton reservacion;
    // End of variables declaration//GEN-END:variables
    private GestorBd controlBd = new GestorBd();

}
